# Generated by Django 5.1.4 on 2024-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('marca', models.CharField(max_length=60)),
                ('almacenamiento', models.CharField(max_length=60)),
                ('proveedor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Computadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('marca', models.CharField(max_length=60)),
                ('almacenamiento', models.CharField(max_length=60)),
                ('proveedor', models.CharField(max_length=60)),
            ],
        ),
    ]
