# Generated by Django 5.1.4 on 2024-12-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Televisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('marca', models.CharField(max_length=60)),
                ('pulgadas', models.IntegerField()),
                ('proveedor', models.CharField(max_length=60)),
            ],
        ),
    ]
